In [1]:
from nn import Linear, Sigmoid, Relu
from loss import BinaryCrossEntropyLoss
from network import NeuralNet
import numpy as np
import logging
logging.basicConfig(format="%(asctime)s %(levelname)s: %(message)s",
                    level=logging.INFO)
logger = logging.getLogger(__name__)

In [2]:
from keras.datasets import mnist


/Users/universe_bright/Workarea/PythonEnvironments/Py39Common/lib/python3.9/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [3]:
(train_X, train_y), (test_X, test_y) = mnist.load_data()
print('X_train: ' + str(train_X.shape))
print('Y_train: ' + str(train_y.shape))
print('X_test:  '  + str(test_X.shape))
print('Y_test:  '  + str(test_y.shape))

X_train: (60000, 28, 28)
Y_train: (60000,)
X_test:  (10000, 28, 28)
Y_test:  (10000,)


In [4]:
# select class 0 and 1 only for binary classification
train_X = train_X[(train_y <= 1)]
train_y = train_y[(train_y <= 1)]
test_X = test_X[(test_y <= 1)]
test_y = test_y[(test_y <= 1)]

In [5]:
# flatten 28 x 28 images to 748 array
train_X = train_X.reshape(len(train_X), -1)
test_X = test_X.reshape(len(test_X), -1)


In [6]:
train_X = train_X / 255.
test_X = test_X / 255.

In [7]:
train_y = train_y.astype(float)
test_y = test_y.astype(float)

In [8]:
len(train_y), len(test_y)

(12665, 2115)

In [9]:
nd_X = len(train_X[0])
print(f"Dimensions, X {nd_X}")
learning_rate = 0.01
net = NeuralNet()
net.add_layer(Linear(nd_X, 64, learning_rate))
net.add_layer(Relu())
net.add_layer(Linear(64, 24, learning_rate))
net.add_layer(Relu())
net.add_layer(Linear(24, 1, learning_rate))
net.add_layer(Sigmoid())

Dimensions, X 784


In [10]:
net.loss = BinaryCrossEntropyLoss()

In [11]:
net.train(train_X, train_y, n_epoch=20)

2024-03-08 22:03:50,244 INFO: Running epoch:    0
2024-03-08 22:03:52,537 INFO: Epoch: 0, Loss:     0.058016

2024-03-08 22:03:54,609 INFO: Running epoch:    2
2024-03-08 22:03:56,871 INFO: Epoch: 2, Loss:     0.004719

2024-03-08 22:03:58,990 INFO: Running epoch:    4
2024-03-08 22:04:01,249 INFO: Epoch: 4, Loss:     0.001333

2024-03-08 22:04:03,391 INFO: Running epoch:    6
2024-03-08 22:04:05,461 INFO: Epoch: 6, Loss:     0.000773

2024-03-08 22:04:07,559 INFO: Running epoch:    8
2024-03-08 22:04:09,745 INFO: Epoch: 8, Loss:     0.000171

2024-03-08 22:04:11,895 INFO: Running epoch:   10
2024-03-08 22:04:14,094 INFO: Epoch: 10, Loss:     0.000108

2024-03-08 22:04:16,205 INFO: Running epoch:   12
2024-03-08 22:04:18,319 INFO: Epoch: 12, Loss:     0.000113

2024-03-08 22:04:20,524 INFO: Running epoch:   14
2024-03-08 22:04:22,611 INFO: Epoch: 14, Loss:     0.000064

2024-03-08 22:04:24,742 INFO: Running epoch:   16
2024-03-08 22:04:26,911 INFO: Epoch: 16, Loss:     0.000038

2024-0

In [12]:
predicted = net.test(test_X, test_y)
predicted.shape


2024-03-08 22:04:33,370 INFO: Number of test data: 2115
2024-03-08 22:04:33,553 INFO: Error of test data:        0.004


(2115, 1)

In [13]:
predicted[0]

array([1.])

In [14]:
predicted = predicted.reshape(len(predicted))
predicted[0]

1.0

In [15]:
from sklearn.metrics import accuracy_score, precision_score, recall_score


In [16]:
len(test_y), len(predicted)

(2115, 2115)

In [17]:
test_y[0:10], predicted[0:10]

(array([1., 0., 1., 0., 0., 1., 0., 0., 1., 1.]),
 array([1.00000000e+00, 2.86051719e-15, 1.00000000e+00, 4.09200846e-19,
        4.03940878e-21, 1.00000000e+00, 9.11934690e-38, 5.16441319e-13,
        1.00000000e+00, 1.00000000e+00]))

In [18]:
y_predicted = (predicted > 0.5).astype(int)
y_predicted[0:10]

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 1])

In [19]:
result = {
    "accuracy": accuracy_score(test_y, y_predicted),
    "precision": precision_score(test_y, y_predicted),
    "recall": recall_score(test_y, y_predicted)
}
result

{'accuracy': 0.9990543735224586,
 'precision': 0.9991189427312775,
 'recall': 0.9991189427312775}