In [1]:
from nn import Linear, Sigmoid, Relu
from loss import BinaryCrossEntropyLoss, MSELoss
from network import NeuralNet
import numpy as np
import logging
logging.basicConfig(format="%(asctime)s %(levelname)s: %(message)s",
                    level=logging.INFO)
logger = logging.getLogger(__name__)

In [2]:
# X_train = np.array([[0,0], [0,1], [1,0], [1,1]])
# y_train = np.array([0, 1, 1, 0])

X_train = np.array(
    [[2.7810836,2.55053003],
    [1.46548937,2.36212507],
    [3.39656168,4.40029352],
    [1.38807019,1.85022031],
    [3.06407232,3.00530597],
    [7.62753121,2.75926223],
    [5.33244124,2.08862677],
    [6.92259671,1.77106367],
    [8.67541865,-0.2420686],
    [7.67375646,3.50856301]]    
)

y_train = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])


In [3]:
learning_rate = 0.01
net = NeuralNet()
net.add_layer(Linear(2, 3, learning_rate))
net.add_layer(Relu())
net.add_layer(Linear(3, 5, learning_rate))
net.add_layer(Relu())
net.add_layer(Linear(5, 1, learning_rate))
# net.add_layer(Linear(2, 1, learning_rate))
net.add_layer(Sigmoid())

In [4]:
net.loss = BinaryCrossEntropyLoss()
# net.loss = MSELoss()

In [5]:
net.train(X_train, y_train, n_epoch=1)

2024-03-08 21:01:42,024 INFO: Running epoch:    0
2024-03-08 21:01:42,030 INFO: Epoch: 0, Loss:        0.676

2024-03-08 21:01:42,030 INFO: Trained model!


0 error 1.9216032289115699
Running on layer: Sigmoid layer.
Running on layer: Linear layer (5, 1), lr=0.01
Linear backward, input:  (1, 5) :  [[0.         0.7443917  0.         0.75316238 0.82366321]]
Linear backward, y_error:  [[0.47960121]]
Linear backward, weight:  (5, 1) :  [[-0.816207  ]
 [ 0.83029491]
 [ 0.37828646]
 [-0.35102462]
 [-0.08010601]]
Running on layer: Relu layer.
Running on layer: Linear layer (3, 5), lr=0.01
Linear backward, input:  (1, 3) :  [[0. 0. 0.]]
Linear backward, y_error:  [[-0.39145386  0.39821044  0.18142664 -0.16835183 -0.03841894]]
Linear backward, weight:  (3, 5) :  [[ 0.66193801  0.67152225  0.4732059   0.28546936 -0.97057734]
 [-0.88581726  0.51082243 -0.88422459 -0.41170964 -0.30045549]
 [ 0.79000073  0.44618195 -0.31825841  0.92927944 -0.79974058]]
Running on layer: Relu layer.
Running on layer: Linear layer (2, 3), lr=0.01
Linear backward, input:  (1, 2) :  [[2.7810836  2.55053003]]
Linear backward, y_error:  [[ 0.0833704   0.47060477 -0.31503579]

In [6]:
predicted = net.test(X_train, y_train)

2024-03-08 21:01:42,034 INFO: Number of test data: 10
2024-03-08 21:01:42,035 INFO: Error of test data:        0.659


In [7]:
predicted = predicted.reshape(-1)
predicted

array([0.48137675, 0.48137675, 0.48137675, 0.48137675, 0.48137675,
       0.50338037, 0.50901915, 0.53763373, 0.55465923, 0.48137675])

In [8]:
for pred, expect in zip(predicted, y_train):
    print("predicted: %.3f, expected: %d abs(diff): %.3f" % (pred, expect, np.abs(pred - expect)))


predicted: 0.481, expected: 0 abs(diff): 0.481
predicted: 0.481, expected: 0 abs(diff): 0.481
predicted: 0.481, expected: 0 abs(diff): 0.481
predicted: 0.481, expected: 0 abs(diff): 0.481
predicted: 0.481, expected: 0 abs(diff): 0.481
predicted: 0.503, expected: 1 abs(diff): 0.497
predicted: 0.509, expected: 1 abs(diff): 0.491
predicted: 0.538, expected: 1 abs(diff): 0.462
predicted: 0.555, expected: 1 abs(diff): 0.445
predicted: 0.481, expected: 1 abs(diff): 0.519
